#!/usr/bin/env python
"""
An example code to demo the use of checkpoint.

To inspect the checkpoint:

python -m tensorflow.python.tools.inspect_checkpoint --file_name=cp/zebra --all_tensors

Output
------
tensor_name:  vs1/a
20.0
tensor_name:  vs1/b
[100.   1.   1.   1.   1.]

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging
from pathlib import Path

import tensorflow as tf

CHECKPOINT_DIR = "/tmp/ml_examples/tf/cp/"
CHECKPOINT_PATH = CHECKPOINT_DIR + "zebra"  # Directory will be cp .  Most files will be prefixed with "zebra"

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example code.
    """
    # Create checkpoint directory if it doesn't exist
    checkpoint_dir = Path(CHECKPOINT_DIR)
    if checkpoint_dir.exists() is False:
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

    tf.reset_default_graph()

    with tf.variable_scope("vs1") as scope:
        a = tf.get_variable("a", [], dtype=tf.float32, initializer=tf.constant_initializer(0))
        a = tf.assign(a, a + 10)

        b = tf.get_variable("b", [5], dtype=tf.float32, initializer=tf.constant_initializer(1))
        c = tf.multiply(b[0], 10)
        d = tf.assign(b[0], c)

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    saver = tf.train.Saver()
    with tf.Session() as s:
        file_name = tf.train.latest_checkpoint(CHECKPOINT_DIR)
        if file_name is not None:
            saver.restore(s, file_name)
            log.info("Checkpoint file %s found. Restoring." % (file_name))
        else:
            log.info("Checkpoint file was not found.")
            s.run(init_op)  # Actually assign initial value to variables

        a_val = s.run(a)
        print(a_val)

        d_val = s.run(d)
        print(d_val)

        saver.save(s, CHECKPOINT_PATH)  # Note using the prefix here.


def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
