#!/usr/bin/env python
"""
An example code to demo the use of TensorFlow

References
----------
https://stackoverflow.com/questions/47840228/tensorflow-error-shape-must-be-rank-0-but-is-rank-1-for-cond-1-switch

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf
import numpy as np

import keras

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example code.
    """
    tf.reset_default_graph()

    a = np.array([1, 2, 3, 4])
    b = np.array([-1, -2, -3, -4])

    x = tf.placeholder(tf.float32, shape=(None), name="x")
    x_mean = tf.reduce_mean(x)

    # If mean is greater than 0, return mean, if not, return 0
    final_result = tf.cond(x_mean > 0, lambda: x_mean, lambda: tf.constant(0, dtype=tf.float32))

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    with tf.Session() as s:
        s.run(init_op)  # Actually assign initial value to variables

        val = s.run(final_result, feed_dict={x: a})  # Returns 2.5
        print("value of x: %f" % (val))

        val = s.run(final_result, feed_dict={x: b})  # Returns 0
        print("value of x: %f" % (val))


def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
