#!/usr/bin/env python
"""
An example code to demo the use of TensorFlow

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def main():
    """Defines an application's main functionality"""

    with tf.variable_scope("addition") as scope:
        a = tf.get_variable("a", (), dtype=tf.int32,
                                         initializer=tf.constant_initializer(1))

        b = tf.get_variable("b", (), dtype=tf.int32,
                                         initializer=tf.constant_initializer(2))

        c = tf.add(a, b)

    init_op = tf.global_variables_initializer()

    with tf.Session() as s:
        s.run(init_op)

        c_value = s.run(c)
        print("Value of c: %d" % (c_value))

if __name__ == "__main__":
    main()
