#!/usr/bin/env python
"""
An example code to demo the use of checkpoint.
This increments the value of a by 10 each time you run the script.

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import sys
import logging
from pathlib import Path

import tensorflow as tf

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def main():
    """Defines an application's main functionality"""
    if len(sys.argv) < 2:
        log.info("gfile <file name>")

    file_name = sys.argv[1]
    lines = tf.gfile.GFile(file_name).readlines()
    for l in lines:
        print(l, end="")


if __name__ == "__main__":
    main()
