#!/usr/bin/env python
"""
An example code to demo the use of checkpoint.
This increments the value of a by 10 each time you run the script.

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging
from pathlib import Path

import tensorflow as tf

CHECKPOINT_DIR = "/tmp/ml_examples/tf/graph1/cp"
GRAPH_DIR = "/tmp/ml_examples/tf/graph1/def"

CHECKPOINT_PATH = CHECKPOINT_DIR + "aimee"  # Files will be prefixed with "aimee"

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example code.
    """
    # Create checkpoint directory if it doesn't exist
    checkpoint_dir = Path(CHECKPOINT_DIR)
    if checkpoint_dir.exists() is False:
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

    tf.reset_default_graph()

    with tf.variable_scope("jungle") as scope:
        lion_ref = tf.get_variable("lion", [], dtype=tf.float32, initializer=tf.constant_initializer(123))
        assign_lion = tf.assign(lion_ref, lion_ref + 27)

    default_graph = tf.get_default_graph()
    graph_def = default_graph.as_graph_def()

    tf.io.write_graph(graph_def, GRAPH_DIR, "animals.pbtxt")

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    saver = tf.train.Saver()
    with tf.Session() as s:
        file_name = tf.train.latest_checkpoint(CHECKPOINT_DIR)
        if file_name is not None:
            saver.restore(s, file_name)
            log.info("Checkpoint file %s found. Restoring." % (file_name))
        else:
            log.info("Checkpoint file was not found.")
            s.run(init_op)  # Actually assign initial value to variables

        a_val = s.run(assign_lion)
        print(a_val)

        saver.save(s, CHECKPOINT_PATH)  # Note using the prefix here.


def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
