#!/usr/bin/env python
"""
An example code to demo the use of tfSessionRunHook

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


class MySessionRunHook(tf.train.SessionRunHook):
    def after_create_session(self, session, coord):
        print("MySessionRunHook.after_create_session() called")

    def begin(self):
        print("MySessionRunHook.begin() called")

    def end(self, session):
        print("MySessionRunHook.end() called")

    def before_run(self, run_context):
        print("MySessionRunHook.before_run() called")

    def after_run(self, run_context, run_values):
        print("MySessionRunHook.after_run() called")


def example():
    """An example code.
    """
    tf.reset_default_graph()

    with tf.variable_scope("vs1") as scope:
        a = tf.get_variable("a", [2, 3], dtype=tf.float32, initializer=tf.constant_initializer(50))
        b = tf.get_variable("b", [2, 3], dtype=tf.float32,
                            initializer=tf.contrib.layers.xavier_initializer(seed=0))

        c = tf.placeholder(tf.float32, [2, 3])
        sum_op1 = tf.add(a, b)
        sum_op = tf.add(sum_op1, c)

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    print("Before 'with tf.train.MonitoredTrainingSession'")

    with tf.train.MonitoredTrainingSession(hooks=[MySessionRunHook()]) as s:
        print("Before s.run(init_op)")
        s.run(init_op)  # Actually assign initial value to variables
        print("After s.run(init_op)")

        print("Before sum = s.run #1 call")
        sum = s.run(sum_op, feed_dict={c: [[100, 200, 300], [400, 500, 600]]})
        print("After sum = s.run #1 call")
        print(sum)

        print("Before sum = s.run #2 call")
        sum = s.run(sum_op, feed_dict={c: [[-10, -20, -30], [-40, -50, -60]]})
        print("After sum = s.run #2 call")
        print(sum)


def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
