#!/usr/bin/env python
"""
An example code to demo the use of TensorFlow

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf
import numpy as np

import keras

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example code.
    """
    tf.reset_default_graph()

    with tf.variable_scope("foo") as scope:
        a = tf.get_variable("a", (), dtype=tf.float32,
                                initializer=tf.initializers.constant(0))
        a = tf.assign(a, 5)
        b = tf.get_variable("b", (), dtype=tf.float32,
                                initializer=tf.initializers.constant(10))

        c = tf.add(a, b)

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    with tf.Session() as s:
        s.run(init_op)  # Actually assign initial value to variables

        val = s.run(c)
        print("value of c: %d" % (val))

def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
