#!/usr/bin/env python
"""
An example code to demo the use of TensorFlow

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf
import numpy as np

import keras

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example code.
    """
    tf.reset_default_graph()

    with tf.variable_scope("foo") as scope:
        counter = tf.get_variable("counter", (), dtype=tf.float32,
                                initializer=tf.initializers.constant(0))
        increment_counter = tf.assign(counter, counter + 1) # as opposed to using tf.add(counter, 1)

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    with tf.Session() as s:
        s.run(init_op)  # Actually assign initial value to variables

        for i in range(5):
            s.run(increment_counter)  # Run the operation WITHOUT returning the result!

        val = s.run(counter)
        print("value of counter: %d" % (val))

def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
