#!/usr/bin/env python
"""
An example code to demo the use of from_tensor_slices without calling tf.Session() or creating an iterator.

References on how to use iterator
---------------------------------
https://www.tensorflow.org/guide/datasets

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf
import numpy as np

import keras

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging

tf.enable_eager_execution()


def example():
    """An example code.
    """
    a = ['apple', 'banana', 'coconut']
    d = tf.data.Dataset.from_tensor_slices(a)

    # Create a sub-array
    d_sub = d.take(2)  # Equivalent of d[0:2]

    for i in d_sub:
        next_a_sub_val = i.numpy()
        print(next_a_sub_val)
        # This outputs:
        # b'apple'
        # b'banana'


def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
