#!/usr/bin/env python
"""
An example code to demo the use of tf.data.Dataset

References on how to use iterator
---------------------------------
https://www.tensorflow.org/guide/datasets

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf
import numpy as np

import keras

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


def example():
    """An example code.
    """
    tf.reset_default_graph()

    a = [1., 3., 5.]
    d = tf.data.Dataset.from_tensor_slices(a)

    b = [2., 4., 6.]
    e = tf.data.Dataset.from_tensor_slices(b)

    h = tf.placeholder(tf.string, shape=[])

    # The difference from from_structure() is additional argument for handle at the beginning.
    it = tf.data.Iterator.from_string_handle(h, output_shapes=d.output_shapes, output_types=d.output_types)
    next_op = it.get_next()

    first_ds_op = d.make_one_shot_iterator()
    second_ds_op = e.make_initializable_iterator()

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    with tf.Session() as s:
        s.run(init_op)  # Actually assign initial value to variables

        h1 = s.run(first_ds_op.string_handle())
        h2 = s.run(second_ds_op.string_handle())
        s.run(second_ds_op.initializer)

        while True:
            try:
                next_a_val = s.run(next_op, {h: h1})
                print(next_a_val)

            except tf.errors.OutOfRangeError:
                print("All data in a have been returned by the iterator")
                break

        while True:
            try:
                next_a_val = s.run(next_op, {h: h2})
                print(next_a_val)

            except tf.errors.OutOfRangeError:
                print("All data in a have been returned by the iterator")
                break


def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
