#!/usr/bin/env python
"""
An example code to demo the use of TensorFlow

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf
import numpy as np

import keras

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging

def example():
    """An example code.
    """
    tf.reset_default_graph()

    with tf.variable_scope("fruit") as scope:
        apple = tf.get_variable("apple", (4, 2), dtype=tf.float32,
                                  initializer=tf.constant_initializer([[1, 10], [2, 20], [3, 30], [4, 40]]))
        scalar = tf.reduce_mean(apple) # scalar
        axis0 = tf.reduce_mean(apple, axis=0) # [2.5, 25]
        axis1 = tf.reduce_mean(apple, axis=1) # [5,5, 11, 16.5, 22]

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    with tf.Session() as s:
        s.run(init_op)  # Actually assign initial value to variables

        val = s.run(scalar)
        print(val)

        val = s.run(axis0)
        print(val)

        val = s.run(axis1)
        print(val)



def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
