#!/usr/bin/env python
"""
An example code to demo the use of TensorFlow

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import tensorflow as tf
import numpy as np

import keras

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging

EPOCH_SIZE = 200


def example():
    """An example code.
    """
    tf.reset_default_graph()

    with tf.name_scope("fruit"):
        apple = tf.Variable(1, trainable=True, name="apple")
        banana = tf.Variable(2, trainable=False, name="banana")
        coconut = tf.Variable(100, trainable=True, name = "coconut")

    vs = tf.trainable_variables() # This creates a list of variables, e.g. [apple, coconut]

    init_op = tf.global_variables_initializer()  # Set up operator to assign all init values to variables

    with tf.Session() as s:
        s.run(init_op)  # Actually assign initial value to variables

        val = s.run(vs)
        print(val) # [1, 100]

def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
