#!/usr/bin/env python
"""
A gensim word2vec example script.


References
----------
https://radimrehurek.com/gensim/models/word2vec.html#usage-examples

Parameter description for Word2Vec:
http://kavita-ganesan.com/gensim-word2vec-tutorial-starter-code/#.XDg3Qs9KhsZ

Updating the model:
https://www.machinelearningplus.com/nlp/gensim-tutorial/

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

from pathlib import Path

import gensim
from gensim.models.word2vec import Word2Vec

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging

MODEL_PATH = "/tmp/ml_examples/word2vec_example.model"


def example():
    """An example.
    """

    parent_dir = Path(MODEL_PATH).parent
    if parent_dir.exists() is False:
        parent_dir.mkdir(parents=True, exist_ok=True)

    text1 = """this is a pen. I love the pen."""

    word_list = gensim.utils.simple_preprocess(text1)

    model = Word2Vec([word_list],
                     size=5,  # Number of dimension for a word vector
                     window=5,
                     min_count=1,
                     workers=4)  # Num threads
    model.save(MODEL_PATH)

    if Path(MODEL_PATH).exists():
        log.info("Model file created at %s" % (Path(MODEL_PATH)))

    model = Word2Vec.load(MODEL_PATH)
    names = ['this', 'is', 'a', 'pen']

    for name in text1.split():
        try:
            v = model[name]
            log.info("Word vector for '%s'" % (name))
            log.info(v)
        except KeyError:
            log.info("%s not in the model" % (name))

def main():
    """Defines an application's main functionality"""
    example()


if __name__ == "__main__":
    main()
