#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import time

def main():
    while True:
        print("I'm up")
        time.sleep(5)

if __name__ == "__main__":
    main()
