#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
A Python example code

Fibonacci sequence
0, 1, 1, 2, 3, 5, 8, 13, 21 ...

__author__ = "Hide Inada"
__copyright__ = "Copyright 2019, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""
import subprocess
import time


def fibonacci(max_num):
    index = 0
    prev = 0
    prev_prev = 0
    sum_of_two_nums = 0

    while sum_of_two_nums < max_num:

        if index == 0:
            prev_prev = 0
            index += 1
            yield 0
            continue
        elif index == 1:
            prev = 1
            index += 1
            yield 1
            continue

        sum_of_two_nums = prev_prev + prev
        prev_prev = prev
        prev = sum_of_two_nums
        index += 1

        yield sum_of_two_nums


def main():
    for num in fibonacci(50):
        print(num)


if __name__ == "__main__":
    main()
